# Generated by Django 5.2.7 on 2025-10-23 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del proveedor', max_length=200)),
                ('contacto', models.CharField(help_text='Persona de contacto', max_length=200)),
                ('telefono', models.CharField(help_text='Teléfono de contacto', max_length=15)),
                ('correo', models.EmailField(max_length=100)),
                ('direccion', models.TextField(help_text='Dirección completa')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Productos_telas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la tela', max_length=200)),
                ('categoria', models.CharField(help_text='Categoría de la tela', max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio por unidad', max_digits=10)),
                ('stock', models.IntegerField(help_text='Cantidad en stock')),
                ('unidad_medida', models.CharField(choices=[('metro', 'Metro'), ('yarda', 'Yarda'), ('rollo', 'Rollo'), ('pieza', 'Pieza')], max_length=10)),
                ('imagen_tela', models.ImageField(blank=True, null=True, upload_to='img_telas/')),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telas', to='app_TelasYProveedores.proveedor')),
            ],
            options={
                'verbose_name': 'Producto Tela',
                'verbose_name_plural': 'Productos Telas',
            },
        ),
    ]
